projectRoot = '/mnt/data/BRPHM/rul-space/work/f1_generator_20261002_v12_s930';
gmatDir = fullfile(projectRoot, 'sim', 'gmat');
inputDirs = { ...
    '/mnt/data/BRPHM/tool-cache/f1_leo600_b00_20261002', ...
    '/mnt/data/BRPHM/tool-cache/f1_leo600_b30_20261002', ...
    '/mnt/data/BRPHM/tool-cache/f1_leo600_b60_20261002'};
outputDir = '/mnt/data/BRPHM/rul-space/work/f1_leo600_import_20261002_attempt1';

assert(isfolder(gmatDir), 'Isolated project copy is missing: %s', gmatDir);
assert(~isfolder(outputDir), 'Refusing to overwrite import attempt: %s', outputDir);
mkdir(outputDir);
addpath(gmatDir);

ids = {'LEO600_B00', 'LEO600_B30', 'LEO600_B60'};
assert(numel(inputDirs) == numel(ids), 'Input directory map does not match orbit IDs');
results = repmat(struct( ...
    'id', '', 'report_file', '', 'eclipse_file', '', 'out_file', '', ...
    'record_step_s', NaN, 'grid_points', 0, 'first_time_s', NaN, ...
    'last_time_s', NaN, 'max_step_error_s', NaN, 'event_count', 0, ...
    'beta_tile_deg', NaN, 'beta_min_deg', NaN, 'beta_max_deg', NaN, ...
    'eclipse_geometry_median_km', NaN, 'checks', {{}}), numel(ids), 1);

for k = 1:numel(ids)
    id = ids{k};
    inputDir = inputDirs{k};
    assert(isfolder(inputDir), 'GMAT input directory is missing: %s', inputDir);
    reportFile = fullfile(inputDir, [id '.csv']);
    eclipseFile = fullfile(inputDir, [id '_eclipse.txt']);
    outputFile = fullfile(outputDir, ['env_' id '.mat']);
    assert(isfile(reportFile), 'Missing GMAT report: %s', reportFile);
    assert(isfile(eclipseFile), 'Missing GMAT eclipse report: %s', eclipseFile);
    assert(~isfile(outputFile), 'Refusing to overwrite import output: %s', outputFile);

    [env, info] = import_gmat(id, ...
        'ReportFile', reportFile, ...
        'EclipseFile', eclipseFile, ...
        'RecordStep', 10.0, ...
        'SaveAs', outputFile, ...
        'Quiet', true);

    assert(numel(info.checks) == 8, '%s did not emit all V1-V8 checks', id);
    assert(all(startsWith(string(info.checks), '[PASS] V')), ...
        '%s has a non-pass importer check', id);
    t = seconds(env.Properties.RowTimes - env.Properties.RowTimes(1));
    assert(numel(t) == 259201, '%s has %d samples; expected 259201', id, numel(t));
    assert(t(1) == 0 && t(end) == 2592000, '%s has an unexpected time span', id);
    assert(max(abs(diff(t) - 10)) < 1e-9, '%s has an unexpected record step', id);
    assert(isfile(outputFile), '%s passed validation but output was not written', id);

    results(k) = struct( ...
        'id', id, 'report_file', reportFile, 'eclipse_file', eclipseFile, ...
        'out_file', outputFile, 'record_step_s', info.record_step, ...
        'grid_points', info.n_grid, 'first_time_s', t(1), ...
        'last_time_s', t(end), 'max_step_error_s', max(abs(diff(t) - 10)), ...
        'event_count', numel(info.events), 'beta_tile_deg', info.beta_tile, ...
        'beta_min_deg', info.beta_span(1), 'beta_max_deg', info.beta_span(2), ...
        'eclipse_geometry_median_km', info.ecl_geom_med_km, ...
        'checks', {info.checks});
    clear env info t
end

manifest = struct( ...
    'schema', 'f1_leo600_import_validation_v1', ...
    'created_utc', char(datetime('now', 'TimeZone', 'UTC', ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ss.SSS''Z''')),
    'semantic_labels_read', false, 'final_label_access', false, ...
    'project_copy', projectRoot, 'importer', fullfile(gmatDir, 'import_gmat.m'), ...
    'results', results);
manifestPath = fullfile(outputDir, 'validation_manifest.json');
assert(~isfile(manifestPath), 'Refusing to overwrite validation manifest: %s', manifestPath);
fid = fopen(manifestPath, 'w');
assert(fid >= 0, 'Could not create validation manifest: %s', manifestPath);
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, jsonencode(manifest), 'char');
fwrite(fid, newline, 'char');
clear cleanup
fprintf('F1_LEO600_IMPORT_VALIDATION_PASS %s\n', manifestPath);
