cd('/mnt/data/BRPHM/rul-space/work/f1_generator_20261002_leo600_v1/sim');
summary = make_dataset('Line', 'both', 'Workers', 12, ...
    'SimMode', 'accelerator', 'Smoke', false, 'MaxAttempts', 1, ...
    'OutRoot', '/mnt/data/BRPHM/rul-space/work/f1_generator_20261002_leo600_v1/generated');
disp(summary);
